name: CI

on:
  push:
    branches: [develop, production]
  pull_request:
    branches: [develop, production]
  schedule:
    - cron: 0 0 * * * # once a day

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.9", "5.10", "6.0"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
