# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "develop", "production" ]
  pull_request:
    branches: [ "develop", "production" ]
  schedule:
    - cron: 0 0 * * * # once a day

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.10.0", "6.0.0"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: swift-actions/setup-swift@2.10.1
      with:
        swift-version: ${{ matrix.swift }}
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
