name: Gitflow Release

on:
  workflow_dispatch:
    inputs:
      version_increment:
        type: choice
        required: true
        description: "Version increment"
        default: "patch"
        options:
          - "major"
          - "minor"
          - "patch"

jobs:
  gitflow-release:
    name: Gitflow Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: gitflow-workflow-action release workflows
        id: gitflow
        uses: hoangvvo/gitflow-workflow-action@0.3.7
        with:
          develop_branch: "develop"
          main_branch: "production"
          merge_back_from_main: true
          version_increment: ${{ inputs.version_increment }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install GitHub CLI
        run: brew install gh
     
